version: '3.4'

services:
  mycrm:
    container_name: MyCRMWeb
    image: ${DOCKER_REGISTRY-}mycrm
    build:
      context: .
      dockerfile: MyCRM/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    restart: unless-stopped
  postgres:
    container_name: MyCRMDb
    image: postgres
    environment:
      POSTGRES_DB: "MyCRM"
      POSTGRES_USER: "admen"
      POSTGRES_PASSWORD: "admen123"
      PGDATA: /data/postgres
    ports:
      - "7758:5432"
    networks:
      - postgres
    restart: unless-stopped
    networks:
      - postgres
networks:
  postgres:
    driver: bridge